services:
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-prod:/usr/share/nginx/html/prod
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8001:8080"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  coturn:
    image: coturn/coturn:latest
    ports:
      - "3479:3478"
      - "3479:3478/udp"
      - "5350:5349"
      - "5350:5349/udp"
    environment:
      - TURNSERVER_ENABLED=1
      - TURNSERVER_REALM=my-realm
      - TURNSERVER_USER=${TURNSERVER_USER}
      - TURNSERVER_VERBOSE=1
      - TURNSERVER_FINGERPRINTS=1
      - TURNSERVER_NO_STUN=0
      - TURNSERVER_NO_TLS=1
      - TURNSERVER_NO_TCP=0

    
volumes:
  web-prod:
  jenkins-home:
