spring:
  datasource:
    url: ${MYSQL_JDBC_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

mqtt:
  broker:
    url: ${MQTT_BROKER_URL}
    topics: server/envInfo, server/event, server/status

openAPI:
  secret: ${OPEN_API_KEY}

file:
  dir: /app/
  video: /app/videos
  video-thumbnail: /app/video-thumbnails
  cam-thumbnail: /app/cam-thumbnails

server:
  error:
    include-exception: false
    include-stacktrace: never
    include-binding-errors: never