spring:
  datasource:
    url: ${MYSQL_JDBC_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  data:
    redis:
      host: dev-redis-1
      password: ${REDIS_PASSWORD}

logging:
  level:
    ssafy:
      age:
        backend: debug

jwt:
  secret: ${JWT_SECRET}

mqtt:
  broker:
    url: ${MQTT_BROKER_URL}
    topics: server/envInfo, server/event

openAPI:
  secret: ${OPEN_API_KEY}

file:
  dir: /app/