spring:
  datasource:
    url: ${MYSQL_JDBC_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

mqtt:
  broker:
    url: ${MQTT_BROKER_URL}
    topics: server/envInfo, server/event, server/status

openAPI:
  secret: ${OPEN_API_KEY}

file:
  video: ${VIDEO_DIR}
  video-thumbnail: ${VIDEO_THUMBNAIL_DIR}
  cam-thumbnail: ${CAM_THUMBNAIL_DIR}
