spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: d8c02ed35fda0c0ffa4dc7f37117972390f3f6672103bbcadb684985aff2e1de

mqtt:
  broker:
    url: "tcp://localhost:1883"
