spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  mvc:
    problem details:
      enabled: true

server:
  tomcat:
    max-http-form-post-size: 5GB

logging:
  level:
    ssafy:
      age:
        backend: debug
    web: debug

jwt:
  secret: d8c02ed35fda0c0ffa4dc7f37117972390f3f6672103bbcadb684985aff2e1de

mqtt:
  broker:
    url: "tcp://localhost:1883"
    topics: server/envInfo, server/event, server/status

openAPI:
  secret: ${OPEN_API_KEY}

file:
  dir: D:\
  video: ${VIDEO_DIR}
  video-thumbnail: ${VIDEO_THUMBNAIL_DIR}
  cam-thumbnail: ${CAM_THUMBNAIL_DIR}
